# Site settings
title: Junwoo Seo Personal Website
description: 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Junwoo Seo
user_description: Third Year Computer Science and Statistics at Penn State University
user_title: Penn State University
email: junwoo93s@gmail.com
twitter_username: junwoo93s
github_username:  junwoo93s
gplus_username:  junwoo93s

# Google-analytics
google-analytics:
  id: "junwoo93s"

exclude: ['package.json', 'src' , 'node_modules']
