# Site settings
title: Junwoo Seo Personal Website
description: 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Junwoo Seo
user_description: Third Year Computer Science and Statistics at Penn State University
user_title: Hello! I am a third year Computer Science major and Statistics minor at Pennsylvania State University. I lived in South Korea until middle school and studied in the U.S. since high school. I believe trying coding once is better than reading hundreds of times. Also love to learn new programming languages and also enhance them on my free time. 
email: junwoo93s@gmail.com
twitter_username: junwoo_seo
github_username:  junwoo93s

# Google-analytics
google-analytics:
  id: "junwoo93s"

exclude: ['package.json', 'src' , 'node_modules']
